# Fix Parameters
EVALUATE_EACH_N_EPOCHS: 1
N_EPOCHS_WITHOUT_IMPROVEMENT_FOR_EARLY_STOPPING: 3
#USE_GENERATOR_ONLY: True
PRETRAINED_WEIGHTS: ''
SHOW_RESULTS_EACH_N_EPOCHS: 999
SKIP_FIRST_N_CONFIGS: 0
ORIGINAL_PHASEMASK_SIZE: [512,512]

# Settings
MODUS: 0 # [0:train | 1:predict]
EVALUATION_METHOD: 1  # ['normal' =0; 'specific'=1]
BEST_CONFIGURATION_ONLY: True
BEST_CONFIGURATION: 22
MODEL_NUMBER: 3 # careful normally 3
#IMAGE_SIZE: [256,256] # Model 1 and 2
IMAGE_SIZE: [512,512] # Model 3
#IMAGE_SIZE: [64,64] #Model 4

# Hyperparameters
N_EPOCHS: 32
STRIDES: 2  # From 2 to 1
PADDING: 'same' # original[same]